 - name: Deploy to Neocities
  # You may pin to the exact commit or the version.
  # uses: bcomnes/deploy-to-neocities@8f42b3ee868450c52d65bfb8cc432bc2f30a3f22
  uses: bcomnes/deploy-to-neocities@v1.1.21
  with:
    # Neocities API token for site to deploy to
    api_token: 
    # Local folder to deploy to neocities
    dist_dir: # default is public
    # Delete orphaned files on neocities that don't exist in distDir
    cleanup: 
    # A glob string that prevents matched files from ever being deleted.
    protected_files: # optional
          
